# Use emacs key bindings
bindkey -e

unsetopt beep

alias vim=nvim
PATH=$PATH:/usr/local/bin

# Do I need this, actually?
zstyle :compinstall filename '/Users/chris/.zshrc'

autoload -Uz compaudit compinit

# Load config files
for config_file (~/.zsh_lib/*.zsh); do
  source $config_file
done

compinit

