# Use emacs key bindings
bindkey -e

unsetopt beep

alias vim=nvim
PATH=$PATH:/usr/local/bin
PATH=$PATH:/Applications/kitty.app/Contents/MacOS/
export IONHOME="$HOME/Dev/bitwise/ion"

# Do I need this, actually?
zstyle :compinstall filename '/Users/chris/.zshrc'

autoload -Uz compaudit compinit

# Load config files
for config_file (~/.zsh_lib/*.zsh); do
  source $config_file
done

compinit


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
