# Use emacs key bindings
bindkey -e

unsetopt beep

# PATH=/usr/local/opt/llvm/bin:$PATH
PATH=$PATH:/usr/local/bin
PATH=$PATH:/usr/local/sbin
PATH=$PATH:/usr/local/opt
PATH=$PATH:/Applications/kitty.app/Contents/MacOS/
PATH=$PATH:~/libs/zig
# export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
# export CPPFLAGS="-I/usr/local/opt/llvm/include"

# Do I need this, actually?
zstyle :compinstall filename '/Users/chris/.zshrc'

autoload -Uz compaudit compinit

# Load config files
for config_file (~/.zsh_lib/*.zsh); do
  source $config_file
done

compinit


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
